---
name: Bundle-Perl-Critic-IncludingOptionalDependencies
version: v1.0.0
author:
  - Elliot Shank <perl@galumph.com
abstract: Install everything Perl::Critic plus its optional dependencies.
license: perl
resources:
  license: http://dev.perl.org/licenses/
provides:
  Bundle::Perl::Critic::IncludingOptionalDependencies:
    file: lib/Bundle/Perl/Critic/IncludingOptionalDependencies.pm
    version: 1
generated_by: Module::Build version 0.2808
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
